global:
  security:
    allowInsecureImages: true

mariadb:
  ## See https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
  enabled: true
  primary:
    persistence:
      enabled: false

  metrics:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/mysqld-exporter
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack

